### ISSUE TITLE
Именование переменных

### ISSUE THREAD

**Issue by coursar** [niyazic97/cashback#1]
https://github.com/niyazic97/cashback/blob/fadd4f5ba9cd65726e127c0ffcf5634319ef7075/src/main/java/ru/itpark/service/CashBackService.java#L7-L10

Имена переменных должны отражать их предназначение. g, q, e заменить на говорящие имена.

**Comment by niyazic97** [comment]
@coursar ,исправил.
https://github.com/niyazic97/cashback/commit/2c39d5d932132731f3533fe77e5e97cf75e6db69
